{{- if .Values.configMap.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "coredns-proxy.fullname" . }}-public
data:
  publicKey: {{ .Values.configmap.publicKey | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "coredns-proxy.fullname" . }}-private
data:
  privateKey: {{ .Values.configmap.privateKey | nindent 4 }}
---
{{- end }}